server.port=8084

spring.datasource.url=jdbc:postgresql://ep-noisy-mountain-aqympuue-pooler.c-8.us-east-1.aws.neon.tech:5432/db_recursos?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zKcU9ku8wMGW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect